STOP_WORDS = {
    "a", "an", "the",
    "is", "are", "was", "were",
    "am", "be", "been", "being",
    "and", "or", "but",
    "if", "else", "than",
    "of", "to", "in", "on", "at",
    "for", "from", "by", "with",
    "as", "into", "over", "under",
    "this", "that", "these", "those",
    "it", "its", "they", "them",
    "their", "he", "she", "his", "her",
    "you", "your", "we", "our",
    "i", "me", "my",
    "can", "could", "should", "would",
    "will", "shall", "may", "might",
    "do", "does", "did",
    "have", "has", "had",
    "not", "no", "yes",
    "also", "very", "more", "most",
    "such", "other", "all", "any", "used",
    "use", "uses", "using", "make", "makes",
    "made", "get", "gets", "got", "go", 
    "goes", "work", "works", "working", 
    "system", "document", "documents", 
    "file", "files", "page", "pages"
}